/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVien;

import JDBC.DialogHelper;
import JDBC.ShareHelper;


/**
 *
 * @author User
 */
public class MainNV extends javax.swing.JFrame {

    /**
     * Creates new form MainNV
     */
    public MainNV() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnLuong = new javax.swing.JLabel();
        btnTK = new javax.swing.JLabel();
        btnhoTro = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnHuongDan = new javax.swing.JLabel();
        btnHDong1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDMK = new javax.swing.JMenuItem();
        mnuInfo = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuTK = new javax.swing.JMenuItem();
        mnuNV = new javax.swing.JMenuItem();
        mnuHDong = new javax.swing.JMenuItem();
        mnuLuong = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FOLT's Sales Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luong1.png"))); // NOI18N
        btnLuong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuongMouseClicked(evt);
            }
        });

        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        btnTK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMouseClicked(evt);
            }
        });

        btnhoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HOTRO1_nv.png"))); // NOI18N
        btnhoTro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhoTroMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hoadon.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HuongDan_nv.png"))); // NOI18N
        btnHuongDan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuongDanMouseClicked(evt);
            }
        });

        btnHDong1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hopdong1.png"))); // NOI18N
        btnHDong1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHDong1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHDong1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lgogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTK)
                    .addComponent(btnLuong)
                    .addComponent(btnHuongDan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHDong1)
                    .addComponent(jLabel11)
                    .addComponent(btnhoTro))
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                .addGap(242, 242, 242))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTK)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuong))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHDong1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhoTro)
                            .addComponent(btnHuongDan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 590));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Version 1.0     |     Bản quyền FOTL’s Team     |     Hotline Mr.Trung - 0362.265.399     |     Website http//fotlsteam.com");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        mnuBar.setBackground(new java.awt.Color(204, 204, 255));
        mnuBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnuBar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hethong.png"))); // NOI18N

        mnuDMK.setText("Đổi mật khẩu");
        mnuDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDMKActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDMK);

        mnuInfo.setText("Thông tin TK");
        mnuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuInfo);

        mnuLogout.setText("Đăng xuất");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogout);
        jMenu1.add(jSeparator4);

        mnuExit.setText("Thoát");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        mnuBar.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chucnang.png"))); // NOI18N

        mnuTK.setText("Tài khoản");
        jMenu2.add(mnuTK);

        mnuNV.setText("Nhân viên");
        jMenu2.add(mnuNV);

        mnuHDong.setText("Hợp đồng");
        jMenu2.add(mnuHDong);

        mnuLuong.setText("Lương");
        jMenu2.add(mnuLuong);

        mnuBar.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lienhe.png"))); // NOI18N

        jMenuItem9.setText("jMenuItem9");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem10");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("jMenuItem11");
        jMenu5.add(jMenuItem11);

        mnuBar.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thongtin.png"))); // NOI18N

        jMenuItem12.setText("jMenuItem12");
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("jMenuItem13");
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("jMenuItem14");
        jMenu6.add(jMenuItem14);

        mnuBar.add(jMenu6);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseClicked
        new ThongTinNV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTKMouseClicked

    private void btnLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuongMouseClicked
        new LuongNV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLuongMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new HoaDonNV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnHuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuongDanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuongDanMouseClicked

    private void btnhoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhoTroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhoTroMouseClicked

    private void btnHDong1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDong1MouseClicked
        new HopDongNV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHDong1MouseClicked

    private void mnuDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDMKActionPerformed
        new Main.DMK().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuDMKActionPerformed

    private void mnuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoActionPerformed
        new ThongTinNV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuInfoActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        if (DialogHelper.confirm(this, "Bạn muốn đăng xuất?")) {
            ShareHelper.USER = null;
            this.dispose();
            new Main.DangNhap(this, true).setVisible(true);
        }
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        if (DialogHelper.confirm(this, "Bạn thật sự muốn thoát?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHDong1;
    private javax.swing.JLabel btnHuongDan;
    private javax.swing.JLabel btnLuong;
    private javax.swing.JLabel btnTK;
    private javax.swing.JLabel btnhoTro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuDMK;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuHDong;
    private javax.swing.JMenuItem mnuInfo;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuLuong;
    private javax.swing.JMenuItem mnuNV;
    private javax.swing.JMenuItem mnuTK;
    // End of variables declaration//GEN-END:variables
}
