/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVien;

import DAO.NhanVienDAO;
import JDBC.ShareHelper;
import MODEL.NhanVien;
import java.util.List;

/**
 *
 * @author ACER
 */
public class ThongTinNV extends javax.swing.JFrame {

    NhanVienDAO dao = new NhanVienDAO();

    /**
     * Creates new form ThongTinNV
     */
    public ThongTinNV() {
        initComponents();
        setLocationRelativeTo(null);
        status();
        load();
    }

    void status() {
        txtMaNV.setEditable(false);
        txtDiaChi.setEditable(false);
        txtEmail.setEditable(false);
        txtGioiTinh.setEditable(false);
        txtTenNV.setEditable(false);
        txtMaHD.setEditable(false);
        txtMaLuong.setEditable(false);
        txtSDT.setEditable(false);
        txtTenTK.setEditable(false);

    }

    void load() {
        try {
            String tk = ShareHelper.USER.getUsername();
            List<NhanVien> list = dao.find(tk);
            for (NhanVien nh : list) {
                Object[] row = {
                    nh.getMaNV(),
                    nh.getTenNV(),
                    nh.getUsername(),
                    nh.getMaHD(),
                    nh.getMaL(),
                    nh.isGioiTinh() ? "Nam" : "Nữ",
                    nh.getSdt(),
                    nh.getGmail(),
                    nh.getDiaChi()};
                txtMaNV.setText(nh.getMaNV());
                txtDiaChi.setText(nh.getDiaChi());
                txtEmail.setText(nh.getGmail());
                txtGioiTinh.setText(nh.isGioiTinh()? "Nam" : "Nữ");
                txtMaHD.setText(nh.getMaHD());
                txtMaLuong.setText(nh.getMaL());
                txtSDT.setText(nh.getSdt());
                txtTenNV.setText(nh.getTenNV());
                txtTenTK.setText(nh.getUsername());

            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHinh = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldienthoai = new javax.swing.JLabel();
        lblvaitro = new javax.swing.JLabel();
        lblhoten = new javax.swing.JLabel();
        lblmatkhau = new javax.swing.JLabel();
        lbldienthoai1 = new javax.swing.JLabel();
        lbldienthoai2 = new javax.swing.JLabel();
        lbldienthoai3 = new javax.swing.JLabel();
        lbldienthoai4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblgioiTinh = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtMaLuong = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 32));

        lbldienthoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldienthoai.setText("MÃ HỢP ĐỒNG");
        jPanel1.add(lbldienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, 32));

        lblvaitro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblvaitro.setText("TÀI KHOẢN");
        jPanel1.add(lblvaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 116, 35));

        lblhoten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblhoten.setText("TÊN NHÂN VIÊN");
        jPanel1.add(lblhoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, 35));

        lblmatkhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblmatkhau.setText("MÃ NHÂN VIÊN");
        jPanel1.add(lblmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 35));

        lbldienthoai1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldienthoai1.setText("MÃ LƯƠNG");
        jPanel1.add(lbldienthoai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 124, 35));

        lbldienthoai2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldienthoai2.setText("SĐT");
        jPanel1.add(lbldienthoai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, -1));

        lbldienthoai3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldienthoai3.setText("EMAIL");
        jPanel1.add(lbldienthoai3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 160, -1));

        lbldienthoai4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldienthoai4.setText("ĐỊA CHỈ");
        jPanel1.add(lbldienthoai4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 160, -1));

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 570, 35));

        lblgioiTinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblgioiTinh.setText("GIỚI TÍNH");
        jPanel1.add(lblgioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 140, 30));
        jPanel1.add(txtTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 570, 35));

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 570, 35));

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 570, 35));

        txtMaLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLuongActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 570, 35));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 570, 35));

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 570, 35));

        txtGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioiTinhActionPerformed(evt);
            }
        });
        jPanel1.add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 570, 35));

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 570, 35));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtMaLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLuongActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioiTinhActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
  new MainNV().setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lbldienthoai;
    private javax.swing.JLabel lbldienthoai1;
    private javax.swing.JLabel lbldienthoai2;
    private javax.swing.JLabel lbldienthoai3;
    private javax.swing.JLabel lbldienthoai4;
    private javax.swing.JLabel lblgioiTinh;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblmatkhau;
    private javax.swing.JLabel lblvaitro;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
